###################
# Ne PAS modifier #
###################
markdown:         kramdown
highlighter:      rouge
permalink:        /:year/:month/:day/:title/
baseurl:          /
paginate:         500
lang:             fr
plugins:
                  - jekyll-seo-tag


#####w#########
# À modifier #
##############
tagline:          'Entrepreneur public'
title:            Frédéric Bardolle
description:      Innovation publique, éthique & IA
inscription:      Pour recevoir les prochains articles par courriel, vous pouvez m'envoyer un *message*.
url:              http://machin.ghitub.io
author:
  name:           'Frédéric Bardolle'
  twitter:        seiteta
social:
  name:           Frédéric Bardolle
  links:
                  - https://twitter.com/seiteta
                  - https://www.linkedin.com/in/fbardolle
